### ISSUE TITLE
Fix automatic deployments to WP.org

### ISSUE THREAD

**Issue by kasparsd** [georgestephanis/two-factor#176]
Currently the plugin is auto-deployed by [a script on WP.org](https://meta.svn.wordpress.org/sites/trunk/api.wordpress.org/public_html/dotorg/github-sync/feature-plugins.php) which has a known issue with creating releases for every pull request, for example.

Let's move to more controlled deploys via Travis. 

See [this thread on Slack](https://wordpress.slack.com/archives/C04L4KCUB/p1491590222161516).
See https://deliciousbrains.com/deploying-wordpress-plugins-travis/

**Comment by joshbetz** [comment]
Any reason not to fix the script on WP.org?

**Comment by kasparsd** [comment]
@joshbetz I guess we could ask @dd32 or @Otto42 if that's possible. There are two major issues with the current script and making changes to it:

1. The deploy script should create releases only for commits to `master`. We probably need a `develop` branch to prepare a release -- all PRs need to be to that branch.

2. We could keep using `trunk` for stable on SVN but we need control over the version number (instead of the automatic date based version). This would require changing the way other plugins using the auto-deploy are developed too.

**Comment by kasparsd** [comment]
@georgestephanis Could you please let us know which triggers have been enabled for the WP.org webhook for this repository?

![webhook-trigger-settings](https://cloud.githubusercontent.com/assets/169055/25947979/60bfcb04-365a-11e7-854b-06fce45b2f2d.png)

**Comment by kasparsd** [comment]
Here is a suggested fix for the existing deploy script on WP.org https://github.com/kasparsd/api.wordpress.org/pull/2/files

**Comment by dd32** [comment]
https://github.com/kasparsd/api.wordpress.org/pull/2/files seems like a sane change to me - I assume the problem is these version bumping commits with no other changes: https://plugins.trac.wordpress.org/changeset/1655004 ?

**Comment by kasparsd** [comment]
@dd32 Yes, we are currently getting a new release for every new pull request :) Thanks for looking into it.

**Comment by dd32** [comment]
@kasparsd Thanks for confirming that! I'll take a look at it tomorrow..

**Comment by dd32** [comment]
Should be fixed with https://meta.trac.wordpress.org/changeset/5498

Let me know if it seems fixed (or broken!)

**Comment by kasparsd** [comment]
Thank you @dd32 -- works great! I opened #178 and no release was created. I merged #165 and it created a release as expected.

**Comment by kasparsd** [comment]
@dd32 Unfortunately this is still happening -- @georgestephanis just opened a pull request and a new version was released https://plugins.trac.wordpress.org/changeset/1663141

**Comment by kasparsd** [comment]
@dd32 I wonder if that happens [because of](https://github.com/kasparsd/api.wordpress.org/blob/master/public_html/dotorg/github-sync/feature-plugins.sh#L84):

```
svn propset -q github:lastSync $LATEST_GIT_REV $WORKING_DIR
```

which makes `svn status -q $WORKING_DIR` return a different status.

**Comment by kasparsd** [comment]
Indeed:

```
$ svn propset -q github:lastSync 11222 trunk
$ svn status                                
 M      trunk
```

**Comment by dd32** [comment]
I was afraid that would happen :) I went looking for an "ignore property changes" option, but there was none, I'd have had to instead use `| grep -v ' M'`.

Instead, I've adjusted the order of operations in https://meta.trac.wordpress.org/changeset/5507 hopefully that'll fix it for good

**Comment by kasparsd** [comment]
Closing as fixed.
