### ISSUE TITLE
FIDO U2F depends on HTTPS but does not indicate the login failure due to HTTP

### ISSUE THREAD

**Issue by valendesigns** [georgestephanis/two-factor#79]
When you attempt to login into the admin with Chrome and a non HTTPS URL you get a failed login attempt. However, there is no useful notification returned back to the user as to why the attempt failed. If the admin has not forced SSL login then this situation becomes possible. Even though it is an edge case, all exceptions and errors should be handled.

As well, you can't create keys in HTTP, and `Failed` is not expressive enough. The user should know why it failed.

**Comment by BandonRandon** [comment]
This should be resolved in #125

**Comment by kasparsd** [comment]
@BandonRandon I think we're still missing a notification on the user profile page.

**Comment by BandonRandon** [comment]
@kasparsd You're right, I saw the notification at https://github.com/georgestephanis/two-factor/pull/125/files#diff-0d7790d2b7baef79f18c7c2ac2765ff4R105 and got confused

**Comment by kasparsd** [comment]
This has been fixed in #125 (for login) and in #162 for the admin UI.
